### ISSUE TITLE
Correct URL to API token

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/weechat-slacklog#13]
In the README, the link to the API token is out of date. The new URL is https://api.slack.com/web#authentication

**Comment by florentferry** [comment]
In the README, the link is again out of date I think. I find my API Token at https://api.slack.com/custom-integrations/legacy-tokens

**Comment by pbrisbin** [comment]
The big warning and the fact that that URL contains "legacy" is not a good sign. I wonder if we should consider this project deprecated. I don't know that any of the original authors still use it (I don't) and any new development should probably start by moving to the new integrations API referenced in that page.

**Comment by jferris** [comment]
I also don't use this project anymore. I agree it should probably be deprecated.
