### ISSUE TITLE
Undefined method 'sub' in 'backlog'

### ISSUE THREAD

**Issue by revoltorb** [thoughtbot/weechat-slacklog#16]
When I run slacklog from the terminal using `ruby ./slacklog.rb fetch API-CODE-HERE` it returns the following error:

```
slacklog.rb:53:in 'backlog': undefined method 'sub' for nil:NilClass (NoMethodError)
   from slacklog.rb:246:in '<main>'
```

Not sure how to go about fixing this, but was hoping you might be able to help.

Running:
- ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
- Arch Linux

**Comment by pbrisbin** [comment]
It's because you're not passing a channel. This results in `backlog(nil, ...` and eventually `nil.gsub(/#...`.

I just checked, and the README seems to be accurate:

```
% ruby ./slacklog.rb fetch API-TOKEN CHANNEL
```

I'm going to go ahead and close this issue, but feel free to re-open if you encounter errors after passing a channel name.
