### ISSUE TITLE
Correct times

### ISSUE THREAD

**Issue by keith** [thoughtbot/weechat-slacklog#7]
I've noticed that the when backlog comes in it uses the current time, not the time the message was actually posted. I'm not sure there's anyway around this though?

**Comment by jalcine** [comment]
I was going to suggest just prefixing the times in the messages themselves myself. But glad to see some discussion on this (despite it being a year old :sob:)

**Comment by pbrisbin** [comment]
So, I don't think `prnt_date_tags` is what we want. Looking at the guide:

```
# display "hello" on core buffer
weechat.prnt("", "hello")

# display "hello" on core buffer, but do not write it to log file
# (version >= 0.3.3 only)
weechat.prnt_date_tags("", 0, "no_log", "hello")
```

By usage, there is no date argument being passed. By comment, it seems the difference is that these messages aren't logged. Either way, I don't think it'll do what we want.

**Comment by jalcine** [comment]
Ah, darn. I'm going to pop into #weechat on Freenode and see if there's something for this.

**Comment by rawdigits** [comment]
prnt_date_tags does what you expect, but you need to give it an integer posix timestamp. slack gives you a float with microseconds. wee-slack use this to print the backlog: https://github.com/rawdigits/wee-slack/blob/master/wee_slack.py#L597

```
weechat.prnt_date_tags(channel_buffer, time_int, tags, data)
```

**Comment by lbolla** [comment]
I'd love this feature. Any chance it can be implemented? I am happy to help, although I have zero experience with Ruby.

**Comment by keith** [comment]
Closing since this is being archived
